# Usa la versión específica de Node.js para el desarrollo de la aplicación React
FROM node:16.16.0-alpine

WORKDIR /app

# Copia los archivos package.json y package-lock.json
COPY package*.json ./

# Instala las dependencias
RUN npm install --legacy-peer-deps

# Copia el resto de la aplicación
COPY . .

# Exponer el puerto 3002 para desarrollo
EXPOSE 3002

# Inicia la aplicación en el puerto 3002
ENV PORT=3002
CMD ["npm", "start"]
